# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JCWeibo' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

pod 'QorumLogs'
pod 'SnapKit'
pod 'SVProgressHUD'
pod 'SDWebImage'
pod 'KILabel'
pod 'FMDB'
pod 'Alamofire'

  # Pods for JCWeibo

end
